FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    kea \
    dnsutils \
    net-tools \
    iputils-ping \
    traceroute \
    tcpdump \
    curl \
    wget \
    vim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/kea/ /var/lib/kea \
    && touch /var/run/kea/logger_lockfile

EXPOSE 67/udp
