apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp-deployment
  labels:
    app: kea-dhcp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kea-dhcp
  template:
    metadata:
      labels:
        app: kea-dhcp
    spec:
      containers:
        - name: kea-dhcp
          image: muruu1/isc-kea:latest
          imagePullPolicy: Always
