apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dhcp-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.20.0/24
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dhcp-pool
  namespace: metallb-system
spec:
  ipAddressPools:
    - dhcp-pool
