apiVersion: v1
kind: Service
metadata:
  name: kea-dhcp
  namespace: dhcp
spec:
  selector:
    name: kea-dhcp
  clusterIP: None
  ports:
    - name: to-server
      port: 67
      targetPort: 67
      protocol: UDP
    - name: heartbeat
      port: 8000
      targetPort: 8000
      protocol: TCP
