apiVersion: v1
kind: Service
metadata:
  name: dhcp-service
  namespace: dhcp
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.20.238
spec:
  ports:
    - name: to-server
      port: 67
      targetPort: 67
      protocol: UDP
    - name: heartbeat
      port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: kea-dhcp
  type: LoadBalancer
