apiVersion: v1
kind: Service
metadata:
  name: dhcp-service
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.20.238
spec:
  ports:
    - name: to-server
      port: 67
      targetPort: 67
      protocol: UDP
  selector:
    app: kea-dhcp
  type: LoadBalancer
