apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kea-dhcp
  namespace: dhcp
spec:
  serviceName: "kea-dhcp"
  replicas: 3
  selector:
    matchLabels:
      app: kea-dhcp
  template:
    metadata:
      labels:
        app: kea-dhcp
    spec:
      initContainers:
        - name: init-config
          image: muruu1/isc-kea:latest
          command:
            [
              "sh",
              "-c",
              "cp /etc/kea/* /etckea && cp /config/$(hostname).conf /etckea/kea-dhcp4.conf && cp /config/update-config.sh /etckea/update-config.sh",
            ]
          volumeMounts:
            - name: kea-etc
              mountPath: /etckea
            - name: kea-cm
              mountPath: /config
      containers:
        - name: kea-dhcp
          image: muruu1/isc-kea:latest # :debug
          imagePullPolicy: Always
          command:
            [
              "sh",
              "-c",
              "sleep 60; sh /etc/kea/update-config.sh && kea-dhcp4 -c /etc/kea/kea-dhcp4.conf",
            ]
          ports:
            - name: bootps
              containerPort: 67
            - name: heartbeat
              containerPort: 8000
          volumeMounts:
            - name: kea-etc
              mountPath: /etc/kea
            - name: kea-data
              mountPath: /var/lib/kea
      volumes:
        - name: kea-etc
          emptyDir: {}
        - name: kea-cm
          projected:
            sources:
              - configMap:
                  name: kea-primary
                  items:
                    - key: kea-dhcp-0.conf
                      path: kea-dhcp-0.conf
              - configMap:
                  name: kea-secondary
                  items:
                    - key: kea-dhcp-1.conf
                      path: kea-dhcp-1.conf
              - configMap:
                  name: kea-backup
                  items:
                    - key: kea-dhcp-2.conf
                      path: kea-dhcp-2.conf
              - configMap:
                  name: kea-config-updater
                  items:
                    - key: update-config.sh
                      path: update-config.sh
  volumeClaimTemplates:
    - metadata:
        name: kea-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-client
        resources:
          requests:
            storage: 1Gi
